#include "IMSDKComm.h"
#include "IMSDKDefine.h"
/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class com_tencent_imsdk_cpphelper_IMSDKCppListener */
#if PLATFORM_ANDROID  
#ifndef _Included_com_tencent_imsdk_cpphelper_IMSDKCppListener
#define _Included_com_tencent_imsdk_cpphelper_IMSDKCppListener
#ifdef __cplusplus
extern "C" {
#endif 
	void Java_com_tencent_imsdk_cpphelper_IMSDKCppListener_onResult(JNIEnv *env, jclass cls, jlong metadataPointer, jlong resultPointer, jint tag, jstring str);
#ifdef __cplusplus
}
#endif
#endif
#endif